---
title: "Ha_DemographicTrend"
author: "Thu Ha Nguyen"
date: "10/30/2018"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(ggplot2)
```


```{r}
final_county <- read_csv("~/jvstats/final_county.csv")
nrow(final_county)
ncol(final_county)
```
#voting age eligible population
```{r}
ggplot(data=final_county, aes(x=YEAR, y=VOTE_ELIGIBLE, color=as.factor(CTYNAME))) +
    geom_line()
```

#employment and income
```{r}
ggplot(data=final_county, aes(x=YEAR, y=EMPLOY.HC04_EST_VC01, color=as.factor(CTYNAME))) +
    geom_line() + ylab("Unemployed; Estimate; Population 16 years and over")

ggplot(data=final_county, aes(x=YEAR, y=INCOME.HC01_EST_VC13, color=as.factor(CTYNAME))) +
    geom_line() + ylab("Households; Estimate; Median income (dollars)")

ggplot(data=final_county, aes(x=YEAR, y=INCOME.HC01_EST_VC02, color=as.factor(CTYNAME))) +
    geom_line() + ylab("Households; Estimate; Less than $10,000")
```

#education
```{r}
ggplot(data=final_county, aes(x=YEAR, y=`BACHELOR'S DEGREE`, color=as.factor(CTYNAME))) +
    geom_line() + ylab("Bachelor degree")
```