---
title: "MYKHE_Merged102718"
author: "My Khe"
date: "10/27/2018"
output: html_document
---

```{r}
#More Population
population17 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/POPULATION/ACS_17_1YR_B01003_with_ann.csv")
#colnames(population10) <- as.character(unlist(population10[1,]))
population17 <- population17[-1, ]
population17 <- population17 %>%
  mutate(YEAR = 2017)
population17 <- population17[ , -c(1,2,5)]

population16 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/POPULATION/ACS_16_5YR_B01003_with_ann.csv")
#colnames(population10) <- as.character(unlist(population10[1,]))
population16 <- population16[-1, ]
population16 <- population16 %>%
  mutate(YEAR = 2016)
population16 <- population16[ , -c(1,2,5)]

population12 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/POPULATION/ACS_12_5YR_B01003_with_ann.csv")
#colnames(population10) <- as.character(unlist(population10[1,]))
population12 <- population12[-1, ]
population12 <- population12 %>%
  mutate(YEAR = 2012)
population12 <- population12[ , -c(1,2,5)]

population08 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/POPULATION/ACS_08_1YR_B01003_with_ann.csv")
#colnames(population10) <- as.character(unlist(population10[1,]))
population08 <- population08[-1, ]
population08 <- population08 %>%
  mutate(YEAR = 2008)
population08 <- population08[ , -c(1,2,5)]

population06 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/POPULATION/ACS_06_EST_B01003_with_ann.csv")
#colnames(population10) <- as.character(unlist(population10[1,]))
population06 <- population06[-1, ]
population06 <- population06 %>%
  mutate(YEAR = 2006)
population06 <- population06[ , -c(1,2,5)]

population <- rbind(population06, population08, population12, population16, 
                         population17)
colnames(population) <- c("CTYNAME", "POPULATION", "YEAR")
View(population)
write.csv(population, file="populationEXTRA.csv")
```

```{r}
#More citizenship
citizen17 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/CITIZENSHIP/ACS_17_1YR_B05001_with_ann.csv")
View(citizen17)
citizen17 <- citizen17 %>%
  mutate(YEAR = 2017) %>%
  select(`GEO.display-label`, `HD01_VD01`, HD01_VD02, HD01_VD03, HD01_VD04, HD01_VD05, HD01_VD06, YEAR) 
#colnames(citizen14) <- as.character(unlist(citizen14[1,]))
citizen17 <- citizen17[-1, ]


citizen16 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/CITIZENSHIP/CITIZENSHIP_2016.csv")
View(citizen16)
citizen16 <- citizen16 <- citizen16 %>%
  mutate(YEAR = 2016) %>%
  select(`GEO.display-label`, `HD01_VD01`, HD01_VD02, HD01_VD03, HD01_VD04, HD01_VD05, HD01_VD06, YEAR) 
#colnames(citizen10) <- as.character(unlist(citizen10[1,]))
citizen16 <- citizen16[-1, ]

citizen12 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/CITIZENSHIP/ACS_12_5YR_B05001_with_ann.csv")
View(citizen12)
citizen12 <- citizen12 <- citizen12 %>%
  mutate(YEAR = 2012) %>%
  select(`GEO.display-label`, `HD01_VD01`, HD01_VD02, HD01_VD03, HD01_VD04, HD01_VD05, HD01_VD06, YEAR) 
#colnames(citizen10) <- as.character(unlist(citizen10[1,]))
citizen12 <- citizen12[-1, ]

citizen08 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/CITIZENSHIP/ACS_08_1YR_B05001_with_ann.csv")
View(citizen08)
citizen08 <- citizen08 <- citizen08 %>%
  mutate(YEAR = 2008) %>%
  select(`GEO.display-label`, `HD01_VD01`, HD01_VD02, HD01_VD03, HD01_VD04, HD01_VD05, HD01_VD06, YEAR) 
#colnames(citizen10) <- as.character(unlist(citizen10[1,]))
citizen08 <- citizen08[-1, ]

citizen06 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/CITIZENSHIP/ACS_06_EST_B05001_with_ann.csv")
View(citizen06)
citizen06 <- citizen06 <- citizen06 %>%
  mutate(YEAR = 2006) %>%
  select(`GEO.display-label`, `HD01_VD01`, HD01_VD02, HD01_VD03, HD01_VD04, HD01_VD05, HD01_VD06, YEAR) 
#colnames(citizen10) <- as.character(unlist(citizen10[1,]))
citizen06 <- citizen06[-1, ]


#colnames(citizen10) ==colnames(citizen14)
citizen <- rbind(citizen06, citizen08, citizen12, citizen16, citizen17)

colnames(citizen) <- c("CTYNAME", "Citizen: Total", "Citizen: US Born", "Citizen: Puerto Rico/US Islands Born", "Citizen: Born Abroad", "Citizen: Naturalization", "Not Citizen", "YEAR")
View(citizen)
write.csv(citizen, file="citizenEXTRA.csv")
```

```{r}
#More education

education17 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/EDUCATION/ACS_17_1YR_S1501_with_ann.csv")
View(education17[ ,c(550:600)])
View(education17)
education17 <- education17 %>%
  mutate(YEAR = 2017) %>%
  select(`GEO.display-label`, HC01_EST_VC02, HC02_EST_VC04, HC02_EST_VC06, HC01_EST_VC08, HC02_EST_VC11, HC02_EST_VC14, HC02_EST_VC15, YEAR)
#colnames(education14) <- as.character(unlist(education14[1,]))
education17 <- education17[-1, ]
colnames(education17) <- c("CTYNAME", "POPULATION 18-24", "HIGHSCHOOL DEGREE", "BACHELOR'S DEGREE", "POPULATION >25", "HIGHSCHOOL DEGREE >25", "BACHELOR'S DEGREE >25", "GRADUATE DEGREE >25", "YEAR")


education16 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/EDUCATION/EDUCATION_2016.csv")
View(education16[ ,c(550:600)])
View(education16)
education16 <- education16 %>%
  mutate(YEAR = 2016) %>%
  select(`GEO.display-label`, HC01_EST_VC02, HC02_EST_VC04, HC02_EST_VC06, HC01_EST_VC08, HC02_EST_VC11, HC02_EST_VC14, HC02_EST_VC15, YEAR)
#colnames(education14) <- as.character(unlist(education14[1,]))
education16 <- education16[-1, ]
colnames(education16) <- c("CTYNAME", "POPULATION 18-24", "HIGHSCHOOL DEGREE", "BACHELOR'S DEGREE", "POPULATION >25", "HIGHSCHOOL DEGREE >25", "BACHELOR'S DEGREE >25", "GRADUATE DEGREE >25", "YEAR")

education12 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/EDUCATION/ACS_12_5YR_S1501_with_ann.csv")
View(education12[ ,c(550:600)])
View(education12)
education12 <- education12 %>%
  mutate(YEAR = 2012) %>%
  select(`GEO.display-label`, HC01_EST_VC01, HC01_EST_VC03, HC01_EST_VC05, HC01_EST_VC07, HC01_EST_VC10, HC01_EST_VC13, HC01_EST_VC14, YEAR)
#colnames(education14) <- as.character(unlist(education14[1,]))
education12 <- education12[-1, ]
colnames(education12) <- c("CTYNAME", "POPULATION 18-24", "HIGHSCHOOL DEGREE", "BACHELOR'S DEGREE", "POPULATION >25", "HIGHSCHOOL DEGREE >25", "BACHELOR'S DEGREE >25", "GRADUATE DEGREE >25", "YEAR")

education08 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/EDUCATION/ACS_08_1YR_S1501_with_ann.csv")
View(education08[ ,c(550:600)])
View(education08)
education08 <- education08 %>%
  mutate(YEAR = 2008) %>%
  select(`GEO.display-label`, HC01_EST_VC01, HC01_EST_VC03, HC01_EST_VC05, HC01_EST_VC06, HC01_EST_VC09, HC01_EST_VC12, HC01_EST_VC13, YEAR)
#colnames(education14) <- as.character(unlist(education14[1,]))
education08 <- education08[-1, ]
colnames(education08) <- c("CTYNAME", "POPULATION 18-24", "HIGHSCHOOL DEGREE", "BACHELOR'S DEGREE", "POPULATION >25", "HIGHSCHOOL DEGREE >25", "BACHELOR'S DEGREE >25", "GRADUATE DEGREE >25", "YEAR")

education06 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/EDUCATION/ACS_06_EST_S1501_with_ann.csv")
View(education06[ ,c(550:600)])
View(education06)
education06 <- education06 %>%
  mutate(YEAR = 2006) %>%
  select(`GEO.display-label`, HC01_EST_VC01, HC01_EST_VC03, HC01_EST_VC05, HC01_EST_VC06, HC01_EST_VC09, HC01_EST_VC12, HC01_EST_VC13, YEAR)
#colnames(education14) <- as.character(unlist(education14[1,]))
education06 <- education06[-1, ]
colnames(education06) <- c("CTYNAME", "POPULATION 18-24", "HIGHSCHOOL DEGREE", "BACHELOR'S DEGREE", "POPULATION >25", "HIGHSCHOOL DEGREE >25", "BACHELOR'S DEGREE >25", "GRADUATE DEGREE >25", "YEAR")

education <- rbind(education06, education08, education12, education16, education17) 
View(education)

#education_cols <- education
#colnames(education_cols) <- as.character(unlist(education_cols[1,]))

colnames(education) <- c("CTYNAME", "POPULATION 18-24", "HIGHSCHOOL DEGREE", "BACHELOR'S DEGREE", "POPULATION >25", "HIGHSCHOOL DEGREE >25", "BACHELOR'S DEGREE >25", "GRADUATE DEGREE >25", "YEAR")


write.csv(education, file = "educationEXTRA.csv")

getwd()
```

```{r}
# More marriage
marriage17 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/MARRIAGE/ACS_17_1YR_S1201_with_ann.csv")
marriage17 <- marriage17 %>%
  mutate(YEAR = 2017) %>%
  select(`GEO.display-label`, HC02_EST_VC01, HC04_EST_VC01, YEAR)
#colnames(marraige14) <- as.character(unlist(marraige14[1,]))
marriage17 <- marriage17[-1, ]

marriage16 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/MARRIAGE/ACS_16_5YR_S1201_with_ann.csv")
marriage16 <- marriage16 %>%
  mutate(YEAR = 2016) %>%
  select(`GEO.display-label`, HC02_EST_VC01, HC04_EST_VC01, YEAR)
#colnames(marraige14) <- as.character(unlist(marraige14[1,]))
marriage16 <- marriage16[-1, ]

marriage12 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/MARRIAGE/ACS_12_5YR_S1201_with_ann.csv")
marriage12 <- marriage12 %>%
  mutate(YEAR = 2012) %>%
  select(`GEO.display-label`, HC02_EST_VC01, HC04_EST_VC01, YEAR)
#colnames(marraige14) <- as.character(unlist(marraige14[1,]))
marriage12 <- marriage12[-1, ]

marriage08 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/MARRIAGE/ACS_08_1YR_S1201_with_ann.csv")
marriage08 <- marriage08 %>%
  mutate(YEAR = 2008) %>%
  select(`GEO.display-label`, HC02_EST_VC01, HC04_EST_VC01, YEAR)
#colnames(marraige14) <- as.character(unlist(marraige14[1,]))
marriage08 <- marriage08[-1, ]

marriage06 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/MARRIAGE/ACS_06_EST_S1201_with_ann.csv")
marriage06 <- marriage06 %>%
  mutate(YEAR = 2006) %>%
  select(`GEO.display-label`, HC02_EST_VC01, HC04_EST_VC01, YEAR)
#colnames(marraige14) <- as.character(unlist(marraige14[1,]))
marriage06 <- marriage06[-1, ]

marriage <- rbind(marriage06, marriage08, marriage12, marriage16, marriage17) 

colnames(marriage) <- c("CTYNAME", "Percent Married", "Percent Divorced", "YEAR")
View(marriage)
write.csv(marriage, file="marriageEXTRA.csv")
```

```{r}
# More Race
race17 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/RACE/ACS_17_1YR_B02001_with_ann.csv")
#colnames(race14) <- as.character(unlist(race14[1,]))
race17 <- race17[ ,-c(1,2, 4,5, 7, 9, 11, 13, 15, 17:23) ]
race17 <- race17 %>%
  mutate(YEAR = 2017) 
colnames(race17) <- c("CTYNAME", "WHITE", "BLACK", "INDIAN", "ASIAN", "HAWAIIAN", "OTHERS", "YEAR")
View(race17)
race17 <- race17[-1,]

race16 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/RACE/ACS_16_5YR_B02001_with_ann.csv")
#colnames(race14) <- as.character(unlist(race14[1,]))
race16 <- race16[ ,-c(1,2, 4,5, 7, 9, 11, 13, 15, 17:23) ]
race16 <- race16 %>%
  mutate(YEAR = 2016) 
colnames(race16) <- c("CTYNAME", "WHITE", "BLACK", "INDIAN", "ASIAN", "HAWAIIAN", "OTHERS", "YEAR")
View(race16)
race16 <- race16[-1,]

race12 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/RACE/ACS_12_5YR_B02001_with_ann.csv")
#colnames(race14) <- as.character(unlist(race14[1,]))
race12 <- race12[ ,-c(1,2, 4,5, 7, 9, 11, 13, 15, 17:23) ]
race12 <- race12 %>%
  mutate(YEAR = 2012) 
colnames(race12) <- c("CTYNAME", "WHITE", "BLACK", "INDIAN", "ASIAN", "HAWAIIAN", "OTHERS", "YEAR")
View(race12)
race12 <- race12[-1,]

race08 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/RACE/ACS_08_1YR_B02001_with_ann.csv")
#colnames(race14) <- as.character(unlist(race14[1,]))
race08 <- race08[ ,-c(1,2, 4,5, 7, 9, 11, 13, 15, 17:23) ]
race08 <- race08 %>%
  mutate(YEAR = 2008) 
colnames(race08) <- c("CTYNAME", "WHITE", "BLACK", "INDIAN", "ASIAN", "HAWAIIAN", "OTHERS", "YEAR")
View(race08)
race08 <- race08[-1,]

race06 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/RACE/ACS_06_EST_B02001_with_ann.csv")
#colnames(race14) <- as.character(unlist(race14[1,]))
race06 <- race06[ ,-c(1,2, 4,5, 7, 9, 11, 13, 15, 17:23) ]
race06 <- race06 %>%
  mutate(YEAR = 2006) 
colnames(race06) <- c("CTYNAME", "WHITE", "BLACK", "INDIAN", "ASIAN", "HAWAIIAN", "OTHERS", "YEAR")
View(race06)
race06 <- race06[-1,]

race <- rbind(race06, race08, race12, race16, race17)
View(race)
write.csv(race, file="raceEXTRA.csv")
```

```{r}
# More Sex and Age
sexage17 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/SEX and AGE/ACS_17_1YR_S0101_with_ann.csv")
#colnames(sexage14) <- as.character(unlist(sexage14[1,]))
sexage17 <- sexage17 %>%
  mutate(YEAR = 2017) %>% 
  select("GEO.display-label", "YEAR", "HC03_EST_VC01", "HC05_EST_VC01", "HC02_EST_VC06", "HC02_EST_VC07", "HC02_EST_VC08", "HC02_EST_VC29")
colnames(sexage17) <- c("CTYNAME", "YEAR", "TOTALMALE", "TOTALFEMALE", "AGE1519", "AGE2024", "AGE2529", "AGE18ABOVE")
sexage17 <- sexage17[-1, ]

sexage16 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/SEX and AGE/ACS_16_5YR_S0101_with_ann.csv")

#colnames(sexage14) <- as.character(unlist(sexage14[1,]))
sexage16 <- sexage16 %>%
  mutate(YEAR = 2016) %>% 
  select("GEO.display-label", "YEAR", "HC02_EST_VC01", "HC03_EST_VC01", "HC01_EST_VC06", "HC01_EST_VC07", "HC01_EST_VC08", "HC01_EST_VC28")
colnames(sexage16) <- c("CTYNAME", "YEAR", "TOTALMALE", "TOTALFEMALE", "AGE1519", "AGE2024", "AGE2529", "AGE18ABOVE")
sexage16 <- sexage16[-1, ]

sexage14 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_5_YEAR/SEX and AGE/ACS_14_5YR_S0101_with_ann.csv")

#colnames(sexage14) <- as.character(unlist(sexage14[1,]))
sexage14 <- sexage14 %>%
  mutate(YEAR = 2014) %>% 
  select("GEO.display-label", "YEAR", "HC02_EST_VC01", "HC03_EST_VC01", "HC01_EST_VC06", "HC01_EST_VC07", "HC01_EST_VC08", "HC01_EST_VC28")

colnames(sexage14) <- c("CTYNAME", "YEAR", "TOTALMALE", "TOTALFEMALE", "AGE1519", "AGE2024", "AGE2529", "AGE18ABOVE")
sexage14 <- sexage14[-1, ]

sexage12 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/SEX and AGE/ACS_12_5YR_S0101_with_ann.csv")

#colnames(sexage14) <- as.character(unlist(sexage14[1,]))
sexage12 <- sexage12 %>%
  mutate(YEAR = 2012) %>% 
  select("GEO.display-label", "YEAR", "HC02_EST_VC01", "HC03_EST_VC01", "HC01_EST_VC06", "HC01_EST_VC07", "HC01_EST_VC08", "HC01_EST_VC28")

colnames(sexage12) <- c("CTYNAME", "YEAR", "TOTALMALE", "TOTALFEMALE", "AGE1519", "AGE2024", "AGE2529", "AGE18ABOVE")
sexage12 <- sexage12[-1, ]

sexage08 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/SEX and AGE/ACS_08_1YR_S0101_with_ann.csv")

#colnames(sexage14) <- as.character(unlist(sexage14[1,]))
sexage08 <- sexage08 %>%
  mutate(YEAR = 2008) %>% 
  select("GEO.display-label", "YEAR", "HC02_EST_VC01", "HC03_EST_VC01", "HC01_EST_VC06", "HC01_EST_VC07", "HC01_EST_VC08", "HC01_EST_VC27")

colnames(sexage08) <- c("CTYNAME", "YEAR", "TOTALMALE", "TOTALFEMALE", "AGE1519", "AGE2024", "AGE2529", "AGE18ABOVE")
sexage08 <- sexage08[-1, ]

sexage06 <- read_csv("/home/jvstats/NEW_DATA/DEMOGRAPHICS_SUPPLEMENTAL/SEX and AGE/ACS_06_EST_S0101_with_ann.csv")

#colnames(sexage14) <- as.character(unlist(sexage14[1,]))
sexage06 <- sexage06 %>%
  mutate(YEAR = 2006) %>% 
  select("GEO.display-label", "YEAR", "HC02_EST_VC01", "HC03_EST_VC01", "HC01_EST_VC06", "HC01_EST_VC07", "HC01_EST_VC08", "HC01_EST_VC27")
colnames(sexage06) <- c("CTYNAME", "YEAR", "TOTALMALE", "TOTALFEMALE", "AGE1519", "AGE2024", "AGE2529", "AGE18ABOVE")
sexage06 <- sexage06[-1, ]

sexage <- rbind(sexage06, sexage08, sexage12, sexage16, sexage17) #Also not merging
View(sexage)
write.csv(sexage, file="sexageEXTRA.csv")
```

```{r}
educationEXTRA <- read_csv("~/jvstats/MYKHE/MYKHE_EXTRA_102718/educationEXTRA.csv")
education <- read_csv("~/jvstats/MYKHE/education.csv")
View(education)
#education.df <- rbind(education, educationEXTRA) why there is the poverty variable
```

```{r}
sexageEXTRA <- read_csv("~/jvstats/MYKHE/MYKHE_EXTRA_102718/sexageEXTRA.csv")
View(sexageEXTRA)
```

